package com.hacka.team11.utils

object PlayersCredits {

    val player_cretdit_map: HashMap<String, Double> = hashMapOf(

        "SC Ganguly" to 10.0,
        "P Kumar" to 7.0,
        "BB McCullum" to 11.0,
        "Z Khan" to 9.0,
        "AA Noffke" to 6.5,
        "JH Kallis" to 9.5,
        "RT Ponting" to 11.0,
        "SB Joshi" to 6.0,
        "DJ Hussey" to 8.0,
        "CL White" to 8.0,
        "Mohammad Hafeez" to 7.5,
        "R Dravid" to 10.0,
        "AB Dinda" to 7.0,
        "W Jaffer" to 8.0,
        "I Sharma" to 8.5,
        "V Kohli" to 7.5,
        "AB Agarkar" to 7.0,
        "M Kartik" to 6.0,
        "MV Boucher" to 8.0,
        "B Akhil" to 5.5,
        "WP Saha" to 7.0,
        "LR Shukla" to 5.5,
        "PA Patel" to 7.0,
        "B Lee" to 9.0,
        "ML Hayden" to 11.0,
        "S Sreesanth" to 8.5,
        "KC Sangakkara" to 10.0,
        "MEK Hussey" to 10.0,
        "JR Hopes" to 7.0,
        "IK Pathan" to 9.0,
        "MS Dhoni" to 12.0,
        "SK Raina" to 9.5,
        "K Goel" to 7.0,
        "PP Chawla" to 8.0,
        "WA Mota" to 5.5,
        "JDP Oram" to 7.0,
        "S Badrinath" to 8.0,
        "MS Gony" to 7.0,
        "M Muralitharan" to 10.0,
        "P Amarnath" to 6.0,
        "Joginder Sharma" to 7.5,
        "Yuvraj Singh" to 12.0,
        "SM Katich" to 8.5,
        "T Kohli" to 7.0,
        "GD McGrath" to 9.5,
        "YK Pathan" to 9.5,
        "B Geeves" to 7.0,
        "M Manhas" to 6.5,
        "SR Watson" to 10.0,
        "M Kaif" to 8.0,
        "MF Maharoof" to 8.0,
        "R Bhatia" to 6.0,
        "DS Lehmann" to 7.0,
        "RA Jadeja" to 7.5,
        "M Rawat" to 6.0,
        "DL Vettori" to 9.0,
        "D Salunkhe" to 6.0,
        "SK Warne" to 9.5,
        "SK Trivedi" to 8.0,
        "G Gambhir" to 11.0,
        "MM Patel" to 8.0,
        "V Sehwag" to 12.0,
        "S Dhawan" to 8.5,
        "L Ronchi" to 8.0,
        "ST Jayasuriya" to 9.0,
        "DJ Thornely" to 7.0,
        "RV Uthappa" to 8.5,
        "PR Shah" to 6.0,
        "R Vinay Kumar" to 7.0,
        "AM Nayar" to 7.0,
        "SM Pollock" to 9.5,
        "Harbhajan Singh" to 9.0,
        "S Chanderpaul" to 9.0,
        "A Nehra" to 9.0,
        "DS Kulkarni" to 7.0,
        "LRPL Taylor" to 9.5,
        "AC Gilchrist" to 10.0,
        "Y Venugopal Rao" to 8.0,
        "VVS Laxman" to 8.5,
        "A Symonds" to 10.0,
        "RG Sharma" to 7.5,
        "SB Styris" to 8.0,
        "AS Yadav" to 6.0,
        "SB Bangar" to 6.0,
        "WPUJC Vaas" to 9.5,
        "RP Singh" to 9.0,
        "PP Ojha" to 8.0,
        "DPMD Jayawardene" to 10.0,
        "Kamran Akmal" to 8.0,
        "Pankaj Singh" to 7.0,
        "S Sohal" to 6.0,
        "Mohammad Asif" to 9.0,
        "VY Mahesh" to 6.0,
        "KD Karthik" to 8.0,
        "Shahid Afridi" to 9.0,
        "MK Tiwary" to 8.0,
        "DJ Bravo" to 9.5,
        "VS Yeligati" to 6.0,
        "MA Khote" to 5.5,
        "GC Smith" to 9.0,
        "D Kalyankrishna" to 6.0,
        "RR Sarwan" to 9.0,
        "VRV Singh" to 7.0,
        "SS Tiwary" to 7.0,
        "Sohail Tanvir" to 9.5,
        "A Kumble" to 10.0,
        "DNT Zoysa" to 8.5,
        "AM Rahane" to 7.0,
        "SD Chitnis" to 6.0,
        "Shoaib Malik" to 8.0,
        "TM Srivastava" to 6.0,
        "DW Steyn" to 10.0,
        "B Chipli" to 6.0,
        "JA Morkel" to 8.5,
        "DB Das" to 6.0,
        "CRD Fernando" to 8.0,
        "MK Pandey" to 6.0,
        "HH Gibbs" to 9.0,
        "Gagandeep Singh" to 6.0,
        "SE Marsh" to 9.0,
        "SA Asnodkar" to 7.0,
        "Umar Gul" to 8.0,
        "Salman Butt" to 8.0,
        "BJ Hodge" to 9.0,
        "SP Fleming" to 9.0,
        "S Vidyut" to 7.0,
        "PJ Sangwan" to 6.0,
        "M Ntini" to 9.0,
        "AB de Villiers" to 9.0,
        "SP Goswami" to 7.0,
        "LPC Silva" to 7.0,
        "DB Ravi Teja" to 6.0,
        "DP Vijaykumar" to 7.0,
        "Misbah -ul - Haq" to 8.0,
        "YV Takawale" to 5.0,
        "RR Raje" to 5.0,
        "U Kaul" to 6.0,
        "DT Patil" to 5.0,
        "S Anirudha" to 6.0,
        "L Balaji" to 8.0,
        "CK Kapugedera" to 8.0,
        "A Chopra" to 7.0,
        "T Taibu" to 8.0,
        "J Arunkumar" to 7.0,
        "SR Tendulkar" to 11.0,
        "DR Smith" to 8.0,
        "AD Mascarenhas" to 8.0,
        "TM Dilshan" to 9.0,
        "A Mishra" to 8.0,
        "Niraj Patel" to 6.0,
        "LA Pomersbach" to 8.0,
        "Iqbal Abdulla" to 7.0,
        "Shoaib Akhtar" to 9.0,
        "Younis Khan" to 9.0,
        "RR Powar" to 7.5,
        "PM Sarvesh Kumar" to 6.0,
        "Abdur Razzak" to 7.0,
        "H Das" to 6.0,
        "A Nel" to 8.0,
        "A Mukund" to 6.0,
        "BAW Mendis" to 9.5,
        "T Thushara" to 7.0,
        "A Flintoff" to 9.0,
        "JP Duminy" to 9.0,
        "R Ashwin" to 8.0,
        "SL Malinga" to 10.0,
        "JD Ryder" to 8.0,
        "KP Pietersen" to 10.0,
        "Kamran Khan" to 6.0,
        "T Henderson" to 6.0,
        "RS Bopara" to 7.0,
        "DP Nannes" to 8.0,
        "AM Salvi" to 7.0,
        "YA Abdulla" to 6.0,
        "VS Malik" to 7.0,
        "FH Edwards" to 8.0,
        "CH Gayle" to 10.0,
        "Harmeet Singh" to 7.0,
        "MC Henriques" to 7.0,
        "R Bishnoi" to 7.0,
        "Yashpal Singh" to 6.0,
        "KV Sharma" to 5.0,
        "PC Valthaty" to 6.0,
        "Anureet Singh" to 6.5,
        "RJ Quiney" to 8.0,
        "AS Raut" to 6.0,
        "RR Bose" to 6.0,
        "KP Appanna" to 6.5,
        "Shoaib Ahmed" to 5.5,
        "AA Bilakhia" to 5.0,
        "AN Ghosh" to 5.0,
        "RE van der Merwe" to 7.0,
        "MN van Wyk" to 8.0,
        "TL Suman" to 6.0,
        "S Tyagi" to 5.0,
        "GR Napier" to 7.0,
        "SM Harwood" to 8.0,
        "LA Carseldine" to 7.0,
        "NV Ojha" to 8.0,
        "M Vijay" to 8.0,
        "SB Jakati" to 7.0,
        "DA Warner" to 9.0,
        "D du Preez" to 7.0,
        "RJ Harris" to 8.0,
        "A Singh" to 6.0,
        "M Morkel" to 8.0,
        "A Mithun" to 7.0,
        "C Nanda" to 6.0,
        "SS Sarkar" to 5.5,
        "AD Mathews" to 8.0,
        "J Botha" to 8.0,
        "Mashrafe Mortaza" to 9.0,
        "Jaskaran Singh" to 7.0,
        "GJ Bailey" to 8.0,
        "AB McDonald" to 7.0,
        "Y Nagar" to 7.0,
        "CK Langeveldt" to 8.0,
        "SS Shaikh" to 6.0,
        "Mohammad Ashraful" to 9.0,
        "RA Shaikh" to 6.0,
        "Anirudh Singh" to 6.0,
        "CA Pujara" to 7.0,
        "OA Shah" to 8.0,
        "SW Tait" to 8.0,
        "A Uniyal" to 6.0,
        "AP Tare" to 6.0,
        "AT Rayudu" to 8.0,
        "AA Jhunjhunwala" to 6.0,
        "P Dogra" to 6.0,
        "R Sathish" to 5.5,
        "R McLaren" to 7.0,
        "AG Murtaza" to 7.0,
        "MS Bisla" to 7.5,
        "EJG Morgan" to 8.0,
        "RS Gavaskar" to 6.5,
        "JM Kemp" to 8.0,
        "S Ladda" to 6.0,
        "Bipul Sharma" to 6.0,
        "SE Bond" to 10.0,
        "KA Pollard" to 8.5,
        "MJ Lumb" to 7.0,
        "DR Martyn" to 9.0,
        "S Narwal" to 5.5,
        "UT Yadav" to 7.0,
        "SJ Srivastava" to 6.0,
        "AB Barath" to 6.0,
        "FY Fazal" to 6.0,
        "AC Voges" to 7.0,
        "MD Mishra" to 6.0,
        "R Sharma" to 8.0,
        "J Theron" to 7.0,
        "NLTC Perera" to 8.0,
        "Mandeep Singh" to 7.0,
        "KM Jadhav" to 7.0,
        "KB Arun Karthik" to 7.0,
        "KAJ Roach" to 8.0,
        "PD Collingwood" to 9.0,
        "C Ganapathy" to 6.0,
        "MB Parmar" to 6.0,
        "SB Wagh" to 7.0,
        "DE Bollinger" to 8.0,
        "JD Unadkat" to 7.0,
        "AP Dole" to 6.0,
        "AN Ahmed" to 6.0,
        "MR Marsh" to 8.0,
        "L Ablish" to 6.0,
        "RS Sodhi" to 7.0,
        "B Sumanth" to 5.0,
        "S Sriram" to 5.0,
        "C Madan" to 5.5,
        "AG Paunikar" to 5.5,
        "AJ Finch" to 7.0,
        "STR Binny" to 6.5,
        "ND Doshi" to 6.0,
        "TG Southee" to 8.0,
        "S Randiv" to 6.0,
        "IR Jaggi" to 5.5,
        "DT Christian" to 8.0,
        "AL Menaria" to 5.5,
        "AUK Pathan" to 7.0,
        "RV Gomez" to 6.0,
        "MA Agarwal" to 7.0,
        "UBT Chand" to 7.5,
        "JEC Franklin" to 8.0,
        "DJ Jacobs" to 8.0,
        "AC Thomas" to 7.0,
        "Sunny Singh" to 5.5,
        "WD Parnell" to 8.5,
        "NJ Rimmington" to 7.0,
        "RN ten Doeschate" to 8.0,
        "S Nadeem" to 6.5,
        "BA Bhatt" to 6.0,
        "JJ van der Wath" to 7.5,
        "S Aravind" to 7.0,
        "R Ninan" to 5.0,
        "Shakib Al Hasan" to 8.0,
        "MS Wade" to 9.0,
        "TD Paine" to 8.5,
        "DH Yagnik" to 6.0,
        "BJ Haddin" to 8.5,
        "J Syed Mohammad" to 5.5,
        "VR Aaron" to 6.5,
        "NL McCullum" to 7.0,
        "JE Taylor" to 8.0,
        "KMDN Kulasekara" to 8.5,
        "TR Birt" to 8.0,
        "Harpreet Singh" to 6.0,
        "M Klinger" to 6.5,
        "P Parameswaran" to 5.5,
        "AC Blizzard" to 8.0,
        "I Malhotra" to 5.0,
        "CA Ingram" to 8.0,
        "B Kumar" to 7.5,
        "CJ Ferguson" to 7.0,
        "AA Kazi" to 5.0,

        )


    val delivery_map: HashMap<Int, String> = hashMapOf(

        0 to "o0_1",
        1 to "o0_2" ,
        2 to "o0_3" ,
        3 to "o0_4" ,
        4 to "o0_5" ,
        5 to "o0_6" ,
        6 to "o1_1" ,
        7 to "o1_2" ,
        8 to "o1_3" ,
        9 to "o1_4" ,
        10 to "o1_5" ,
        11 to "o1_6" ,
        12 to "o2_1" ,
        13 to "o2_2" ,
        14 to "o2_3" ,
        15 to "o2_4" ,

        16 to "o2_5" ,
        17 to "o2_6" ,
        18 to "o3_1" ,
        19 to "o3_2" ,
        20 to "o3_3" ,
        21 to "o3_4" ,
        22 to "o3_5" ,
        23 to "o3_6" ,
        24 to "o4_1" ,
        25 to "o4_2" ,
        26 to "o4_3" ,
        27 to "o4_4" ,
        28 to "o4_5" ,
        29 to "o4_6" ,
        30 to "o5_1" ,
        31 to "o5_2" ,
        32 to "o5_3" ,
        33 to "o5_4" ,
        34 to "o5_5" ,
        35 to "o5_6" ,
        36 to "o6_1" ,
        37 to "o6_2" ,
        38 to "o6_3" ,
        39 to "o6_4" ,
        40 to "o6_5" ,
        41 to "o6_6" ,
        42 to "o7_1" ,
        43 to "o7_2" ,
        44 to "o7_3" ,
        45 to "o7_4" ,
        46 to "o7_5" ,
        47 to "o7_6" ,
        48 to "o8_1" ,
        49 to "o8_2" ,
        50 to "o8_3" ,
        51 to "o8_4" ,
        52 to "o8_5" ,
        53 to "o8_6" ,
        54 to "o9_1" ,
        55 to "o9_2" ,
        56 to "o9_3" ,
        57 to "o9_4" ,
        58 to "o9_5" ,
        69 to "o9_6" ,
        60 to "o10_1" ,
        61 to "o10_2" ,
        62 to "o10_3" ,
        63 to "o10_4" ,
        64 to "o10_5" ,
        65 to "o10_6" ,
        66 to "o11_1" ,
        67 to "o11_2" ,
        68 to "o11_3" ,
        69 to "o11_4" ,
        70 to "o11_5" ,
        71 to "o11_6" ,
        72 to "o12_1" ,
        73 to "o12_2" ,
        74 to "o12_3" ,
        75 to "o12_4" ,
        76 to "o12_5" ,
        77 to "o12_6" ,
        78 to "o13_1" ,
        79 to "o13_2" ,
        80 to "o13_3" ,
        81 to "o13_4" ,
        82 to "o13_5" ,
        83 to "o13_6" ,
        84 to "o14_1" ,
        85 to "o14_2" ,
        86 to "o14_3" ,
        87 to "o14_4" ,
        88 to "o14_5" ,
        89 to "o14_6" ,
        90 to "o15_1" ,
        91 to "o15_2" ,
        92 to "o15_3" ,
        93 to "o15_4" ,
        94 to "o15_5" ,
        95 to "o15_6" ,

        96 to "o16_1" ,
        97 to "o16_2" ,
        98 to "o16_3" ,
        99 to "o16_4" ,
        100 to "o16_5" ,
        101 to "o16_6" ,

        102 to "o17_1" ,
        103 to "o17_2" ,
        104 to "o17_3" ,
        105 to "o17_4" ,
        106 to "o17_5" ,
        107 to "o17_6" ,

        108 to "o18_1" ,
        109 to "o18_2" ,
        110 to "o18_3" ,
        111 to "o18_4" ,
        112 to "o18_5" ,
        113 to "o18_6" ,


        114 to "o19_1" ,
        115 to "o19_2" ,
        116 to "o19_3" ,
        117 to "o19_4" ,
        118 to "o19_5" ,
        119 to "o19_6" ,






















        )


}